name: gipms
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 #any

  cupertino_icons: ^1.0.6
  flutter_bloc:
  dio:
  get_it:
  dartz:
  logger:
  shared_preferences:  
  jwt_decode: 
  dart_jsonwebtoken:
  mobile_scanner: 
  pretty_qr_code: 
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_gen:
  output: ./lib/gen

flutter:
  uses-material-design: true
  generate: true 

  assets:
    - assets/images/kaf_logo.png
    - assets/images/logo-gif-Animate.gif
    - assets/images/appiconfg.svg
    - assets/images/nopic.png

